Repository tuananh0405-collab/w4y, pull requests merged in 2025-07, with the labels that each got.

#19 Completed task Chat API
  app.js
  controllers/chat.controller.js
  events/onSetActiveConversation.js
  middlewares/auth.middleware.js
  routes/chat.routes.js
Labels: enhancement

#21 Merge branch 'QuanNM/feature/job-posts' into initial
  controllers/job.controller.js
  models/job.model.js
  models/jobCategory.model.js
  package-lock.json
  package.json
  routes/job.routes.js
Labels: enhancement

#24 Hieu pd/applicant
  controllers/application.controller.js
  controllers/job.controller.js
  routes/application.routes.js
  routes/job.routes.js
Labels: enhancement

#25 Merge branch 'QuanNM/feature/recommended-jobs" into 'initial'
  app.js
  config/env.js
  controllers/applicant.controller.js
  controllers/chat.controller.js
  controllers/job.controller.js
  controllers/jobCategory.controller.js
  controllers/jobSkill.controller.js
  controllers/user.controller.js
  database/chromadb.js
  models/applicantProfile.model.js
  models/job.model.js
  models/jobSkill.model.js
  package-lock.json
  package.json
  routes/job.routes.js
  routes/jobCategory.routes.js
  routes/jobSkill.routes.js
  services/chroma.service.js
Labels: enhancement

#26 Merge branch 'QuanNM/fix/job-salary-range' into 'initial'
  app.js
  controllers/job.controller.js
  models/job.model.js
  services/chroma.service.js
Labels: invalid

#34 Merge branch 'AnhVT/bug-fixings' into 'initial'
  controllers/auth.controller.js
  utils/verifyEmailTemplate.js
Labels: bug, invalid

#39 Hot fixes to make AI job recommendation feature work again
  app.js
  controllers/applicant.controller.js
  controllers/job.controller.js
  models/applicantProfile.model.js
Labels: enhancement, invalid

#40 Push final fixes to production
  controllers/applicant.controller.js
  controllers/application.controller.js
  controllers/auth.controller.js
  controllers/job.controller.js
  models/applicantProfile.model.js
  routes/application.routes.js
  utils/email-template.js
Labels: bug, enhancement
